/* eslint-disable linebreak-style */
export default {
  products: [
    {
      _id: "111111111111111111111111",
      name: "Full Zip Running Shirts",
      category: "Shirts",
      image: "images/product-1.jpg",
      price: 60,
      brand: "Hiskywin",
      rating: 1,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "222222222222222222222222",
      name: "Nike Full-Zip Hoodie Mens Workout Sweatshirt",
      category: "Shirts",
      image: "images/product-2.jpg",
      price: 70,
      brand: "Nike",
      rating: 5,
      numReviews: 51,
      countInStock: 2,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleeve Hoodie",
      category: "Shirts",
      image: "images/product-3.jpg",
      price: 59,
      brand: "Adidas",
      rating: 4,
      numReviews: 45,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sportstyle Tricot Joggers",
      category: "Pants",
      image: "images/product-4.jpg",
      price: 90,
      brand: "Under Armour",
      rating: 2.5,
      numReviews: 199,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Champion Mens Graphic Powerblend Fleece Jogger",
      category: "Pants",
      image: "images/product-5.jpg",
      price: 85,
      brand: "Champion",
      rating: 4.6,
      numReviews: 75,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Aelfric Eden Mens Joggers Pants Long Multi-Pockets",
      category: "Pants",
      image: "images/product-6.jpg",
      price: 86,
      brand: "Aelfric Eden",
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
